# Generated by Django 4.0.6 on 2022-07-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_alter_employee_emp_id_alter_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/message_photos'),
        ),
    ]
