# Generated by Django 4.0.6 on 2022-07-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='text',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
