# Generated by Django 4.0.6 on 2022-07-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0006_alter_employee_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='binary',
            field=models.BinaryField(blank=True, max_length=1000, null=True),
        ),
    ]
