# Generated by Django 4.0.6 on 2022-07-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0009_alter_employee_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='text',
        ),
    ]
