# Generated by Django 4.0.6 on 2022-07-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0010_remove_employee_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='binary',
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.BinaryField(blank=True, max_length=1000, null=True),
        ),
    ]
